spring:
  application:
    name: Khaopiyoji
  datasource:
    url: jdbc:mysql://localhost:3306/Khaopiyoji?createDatabaseIfNotExist=true
    username: root
    password: Gautam@23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  server:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB
  redis:
    uri: redis://default:VLR4xLH3BRbRRRNYjVHPjjsfPFNc1VIo@redis-15154.crce179.ap-south-1-1.ec2.redns.redis-cloud.com:15154
    port: 15154
  mail:
    host: smtp.gmail.com
    port: 587
    username: vikrantsharma232529@gmail.com
    password: xacm zgmc offt cnie
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
